details around saving outputs

diff --git a/run b/run
--- a/run
+++ b/run
@@ -82,7 +82,6 @@ if [[ $ANTS_EXITSTATUS == 0 ]]; then
       mv $(find "$BIDS_OUTPUT_DIR" -type f | grep csv) "$LOOSE_DIR"
       mv $(find "$BIDS_OUTPUT_DIR" -type f | grep png) "$LOOSE_DIR"
       mv $(find "$BIDS_OUTPUT_DIR" -type f | grep desc-thickness) "$LOOSE_DIR"
-
       rm -rf "$BIDS_OUTPUT_DIR"
   elif [[ $inputFormat = 'manual' ]]; then
       # move everything in outputs folder to a single directory and zip
@@ -105,15 +104,14 @@ if [[ $ANTS_EXITSTATUS == 0 ]]; then
   else
     error_exit "Unable to determine input format..."
   fi
-
-  # Clean up
-  #rm -rf "$WORKING_DIR"
-  rm $(find "$GEAR_OUTPUT_DIR" -maxdepth 1 -type f | grep -v antsct | grep -v loose) || echo "No loose files in output folder."
-  mv $LOOSE_DIR/* $GEAR_OUTPUT_DIR
-  rmdir $LOOSE_DIR
-
 fi
 
+# Clean up
+#rm -rf "$WORKING_DIR"
+rm $(find "$GEAR_OUTPUT_DIR" -maxdepth 1 -type f | grep -v antsct | grep -v loose) || echo "No loose files in output folder."
+mv $LOOSE_DIR/* $GEAR_OUTPUT_DIR
+rmdir $LOOSE_DIR
 rm -rf "$ANTS_OUTPUT_DIR"
+
 echo -e "Wrote: $(ls -lh $GEAR_OUTPUT_DIR)"
 exit $ANTS_EXITSTATUS
